db_path = "state/db"
filter_path = "state/filter"

# 0.1GB in bytes
filter_bytes = 100_000_000
filter_expected_entries = 100_000_000
filter_checkpoint_secs = 30

label_map = "label_map.yaml"
workers = 1
